### ISSUE TITLE
Usage in an offline-only environment by copying settings/assets possible?

### ISSUE THREAD

**Issue by enolive** [ani-memes/AMII#101]
I like this plugin very much.

Regrettably, one of my working devices is behind a "firewall of death" without the chance of ever going online, not even with a proxy.

Is it possible to use AMII in this environment? I tried to copy the `amiiAssets` folder from an online device into the config folder of intellij on the offline device, but AMII stillt tells me that it has to go online first. Is there a different settings location I have to copy/modify to make it work?

**Comment by Unthrottled** [comment]
> I tried to copy the amiiAssets folder from an online device into the config folder of intellij on the offline device,

That should work if you put in the directory holding the [Intellij config](https://www.jetbrains.com/help/idea/tuning-the-ide.html#config-directory). I put it there so that way if you use AMII on multiple IDEs, it doesn't re-download half a gig of data, (because I am paying for bandwidth out :smile: )

So just move the `amiiAssets` one directory up and it should work.

![Screenshot from 2021-04-15 16-19-30](https://user-images.githubusercontent.com/15972415/114939652-5fd94900-9e06-11eb-80e6-1cfbcff37cec.png)
:point_up: Shows that the `amiiAssets` directory is hanging out with the other IDE config directories and has contents in it.

If it doesn't I'll ask about the contents of the assets directory next. 

Thanks!

**Comment by enolive** [comment]
thanks, I got it running! I might had some problems with the IDE still running on Windows, but after a restart of the machine it suddenly started working. 

On a side note, version 0.9.2 seems to have trouble with working offline (there are some exceptions that occur) so I downgraded to 0.8.2. 

Netherheless, it works on both versions, you can close the issue!

**Comment by Unthrottled** [comment]
> On a side note, version 0.9.2 seems to have trouble with working offline

I'll have to look into that, I'll close the issue once I've verified this is not an issue or I have fixed it. 

Thanks for the follow up!
